### PR TITLE
added  -i / -max-iterations option

### PR DESCRIPTION
**Pull request by de-code**
I was also considering implementing `eps` / stopping when the graph becomes stable. But need to think about how to best implement that.

(This PR is based on the previous PR, probably best to merge the other PR first)

### CODE REVIEW

**Comment by frankmcsherry** [comment]
If you want to check it out, there are some details about PageRank with epsilon and one way to do it here:

   https://github.com/frankmcsherry/blog/blob/master/posts/2017-08-21.md

There is also some code in the timely repo, but it is much less optimized than this code.

One big difference is that you lay out the data differently: this project lays the data out by edge destination, so that accumulation happens without random access / lookups. When you want to do "sparse" work, you typically want to lay the data out by edge source.

**Comment by frankmcsherry** [comment]
Also looks good to me; thank you!

Fwiw (no need to update) there are a few Rust idiomatic things that may make the code less awkward looking. Not that they'll necessarily make it fully pleasant by themselves, though. :)

For example

```rust
match peer_output_path {
    Some(ref path) => write_pagerank_values_to(&path, &src, index, peers, nodes),
    None => {}
}
```

can be rewritten as 

```rust
if let Some(ref path) = peer_output_path {
    write_pagerank_values_to(&path, &src, index, peers, nodes);
}
```

or (less clearly, I find) as

```rust
peer_output_path.as_ref().map(|path| write_pagerank_values_to(&path, &src, index, peers, nodes));
```

**Comment by de-code** [comment]
Thank you. Both for the pointing me to the _sparse_ solution and the Rust advise. I will have a look. At this moment I don't need fully optimized but to "just work" for about 270 M edges. But the epsilon would be good anyway just to know when it's stable (but of course if it is not much effort I'll take the more optimized version).

I was also considering wrapping it as a Python library but I think I am getting carried away.

I agree, I prefer the second option. I'll use that next time.

**Comment by frankmcsherry** [comment]
> At this moment I don't need fully optimized but to "just work" for about 270 M edges.

I would double check that it is producing the outputs that you want, btw. There is not universal agreement on what pagerank values should be, especially wrt "pre-blending" or "post-blending" or "normalized to sum to 1.0" vs "not normalized at all". There should be a simple graph-agnostic transformation from the output values to any of these, but do check before you plug them in somewhere, and complain if you don't like how they turn out. :)

**Pull request merged**
